ValueError: dictionary update  #0 has length 1
in order to fix the ValueError: dictionary update sequence element #0 has length 1; 2 is required . the following is addded.
                    try:
                	    o.update(e)
                    except:
                        pass